version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - aws cloudformation package --template-file sam.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yml

artifacts:
  files:
    - sam.yml
    - packaged.yml
