AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Pizza Pre-signup Service

Parameters:
  Environment:
    Description: The environment
    Type: String

Resources:
  PreSignupServiceLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - '-'
        - - 'serverlesspizza'
          - !Ref Environment
          - 'pre-signup-lambda'
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          REGION: !Sub ${AWS::Region}
          ACCOUNT_ID: !Sub ${AWS::AccountId}
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
        - AWSLambdaSQSQueueExecutionRole
        - AmazonSQSFullAccess

  PreSignUpSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join
        - '-'
        - - 'serverlesspizza'
          - !Ref Environment
          - 'pre-signup-lambda'
      DelaySeconds: 5

Outputs:
  SqsQueue:
    Value: !GetAtt PreSignUpSqsQueue.Arn
    Description: Sqs queue
    Export:
      Name: !Sub ${Environment}-pre-signup-sqs-queue
